### ISSUE TITLE
Could still be made to work?

### ISSUE THREAD

**Issue by coughlanio** [timdorr/spotifeed#30]
So, I spent a day or so a few weeks back, re-implementing this in Javascript running on Cloudflare Workers, using Workers KV for caching.

I recently encountered the same issue you've been having with the deprecation of the Spotify anonymous CDN, and started working on a workaround, and I'm curious if you've attempted the same?

Basically, I replace the enclosure URLs with a URL resource hosted on my domain, which is served by the following endpoint:

```javascript
router.get('/episode/:id', async (ctx) => {
    const { params: { id } } = ctx

    const cachedEpisode = await DESPOTKV.get(`episode:${id}`)

    if (cachedEpisode) {
        ctx.response.headers.location = cachedEpisode
        ctx.status = 301
        return
    }

    const re = /^.*=exp=(?<expiresAt>\d+).*/

    const response = await fetch(`https://spclient.wg.spotify.com/soundfinder/v1/unauth/episode/${id}/com.apple.fps.1_0`, {
        method: "GET"
    })
    
    const jsonResponse = await response.json()
    
    const {url: [_, url]} = jsonResponse

    const match = re.exec(url)

    await DESPOTKV.put(`episode:${id}`, url, {expiration: match.groups.expiresAt})

    ctx.response.headers["location"] = url
    ctx.response.headers["Content-Type"] = "audio/mp4"
    ctx.status = 301
})
```

I think the only thing preventing this from working, is the Spotify server doesn't respond with the correct Content-Type header, so it's not working in Apple Podcasts or PocketCasts:

```sh
Content-Type: application/octet-stream
Accept-Ranges: bytes
Content-Length: 71094433
```

The files will download over HTTP, and play in VLC though, as an `audio/mp4|m4a`.

Have you tried anything like this?

**Comment by coughlanio** [comment]
So, it seems like it doesn't download the full file, but the first chunk of audio padded out to the full expected content size, which leads me to believe it is indeed an HLS stream as you pointed out 🤔

**Comment by LeoNatan** [comment]
If those are indeed HLS chunks, why not just recreate the playlist file on the spotifeed server, and serve that in the RSS feed?

**Comment by LeoNatan** [comment]
Yes, I think so, at least on modern podcast clients. m3u and m3u8 are valid HLS playlist documents, which should be readable by modern clients. Even if not by all clients, having support for a few players that support it would still be better than nothing.

**Comment by coughlanio** [comment]
So when I take the m3u file that's generated by the embed, playback stops after ~10s.

```m3u
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-TARGETDURATION:1000000
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://4de8ea56812a762c61d13c11240557a36ec0fbab",KEYFORMATVERSIONS="1",KEYFORMAT="com.apple.streamingkeydelivery"
#EXT-X-MAP:URI="https://audio4-ak-spotify-com.akamaized.net/audio/4de8ea56812a762c61d13c11240557a36ec0fbab?__token__=exp=1621517171~hmac=e9567fe4ae0fd841044791a66f461aa85d5cf4041ca253231bd2ffeb125cf5a9",BYTERANGE="6349@0"
#EXTINF:10.00780045351474,
#EXT-X-BYTERANGE:162843@6349
https://audio4-ak-spotify-com.akamaized.net/audio/4de8ea56812a762c61d13c11240557a36ec0fbab?__token__=exp=1621517171~hmac=e9567fe4ae0fd841044791a66f461aa85d5cf4041ca253231bd2ffeb125cf5a9
#EXTINF:10.00780045351474,
#EXT-X-BYTERANGE:162247@169192
https://audio4-ak-spotify-com.akamaized.net/audio/4de8ea56812a762c61d13c11240557a36ec0fbab?__token__=exp=1621517171~hmac=e9567fe4ae0fd841044791a66f461aa85d5cf4041ca253231bd2ffeb125cf5a9
#EXTINF:9.984580498866215,
#EXT-X-BYTERANGE:161649@331439
...
```

**Comment by LeoNatan** [comment]
What player are you using? I think you can use VLC to debug why it stops.

**Comment by timdorr** [comment]
Yeah, the first chunk appears to be normal MP4, but subsequent chunks are not. 

For reference, in the player (at least for the embed), they are using `Range: bytes=` requests to grab each chunk and assembling them as an ArrayBuffer on a MediaSource. I've been trying to emulate what they are doing locally, but haven't been able to get the element to play even the first 10 seconds.

**Comment by yoshimo** [comment]
https://github.com/librespot-org/librespot interfaces with spotify too, maybe it could help with the documentation aspect?

**Comment by yoshimo** [comment]
> 
> 
> Yeah, the first chunk appears to be normal MP4, but subsequent chunks are not.
> 
> For reference, in the player (at least for the embed), they are using `Range: bytes=` requests to grab each chunk and assembling them as an ArrayBuffer on a MediaSource. I've been trying to emulate what they are doing locally, but haven't been able to get the element to play even the first 10 seconds.

There is a browser request to:
https://spclient.wg.spotify.com/widevine-license/v1/unauth/audio/license
Firefox shows a WV CDM icon.
I think we are out of luck here.

**Comment by LeoNatan** [comment]
Looking at https://ogjre.com/

There seems to be an embedded player there, with an anonymous Spotify player. Couldn’t that player’s HLS playlist be taken?

**Comment by timdorr** [comment]
That's just the Spotify embed, which I'm taking from. From what I can tell, they aren't doing any EME stuff on that audio. They make a request to the Widevine endpoint, but that's just to get the content ID and doesn't appear to have any encryption or secret stuff on it. I get the same bytes when I download that file and what's going into the SourceBuffer on the embed. I just have no idea why they are valid for the MediaSource in the embed, but invalid for any other player.

**Comment by coughlanio** [comment]
Any chance you can share you progress? Been butting my head up against it for a few days now.

I've created a temp Discord server here, if anyone wants to try and tackle it together: https://discord.gg/yNeckPy4BQ

**Comment by Funatiker** [comment]
I have the feeling that not all spotify exclusive podcasts use widevine. I think (some of) those exclusive podcasts that have target advertising go through Megaphone.

**Comment by marc1307** [comment]
Hi, i have no idea how hls/dash works, but i looked through the media file. It seems to have the dash control structure hard backed in to it. 

control stuff is not set dynamically by the cdn. the range header just splits file, but does not 'move' a segment or its headers.

`00000000:  0000 0020 6674 7970 6973 6f6d 0000 0000 6973 6f38 6d70 3431  :... ftypisom....iso8mp41
00000018:  6461 7368 636d 6663 0000 03fb 6d6f 6f76 0000 006c 6d76 6864  :dashcmfc....moov...lmvhd
00000030:  0000 0000 dccc 27a5 dccc 27a5 0000 ac44 0000 0000 0001 0000  :......'...'....D........
00000048:  0100 0000 0000 0000 0000 0000 0001 0000 0000 0000 0000 0000  :........................
00000060:  0000 0000 0001 0000 0000 0000 0000 0000 0000 0000 4000 0000  :....................@...
00000078:  0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000  :........................
00000090:  0000 0002 0000 0087 6d65 7461 0000 0000 0000 0020 6864 6c72  :........meta....... hdlr
000000a8:  0000 0000 0000 0000 4944 3332 0000 0000 0000 0000 0000 0000  :........ID32............
000000c0:  0000 005b 4944 3332 0000 0000 15c7 4944 3304 0000 0000 0043  :...[ID32......ID3......C
000000d8:  5052 4956 0000 0039 0000 6874 7470 733a 2f2f 6769 7468 7562  :PRIV...9..https://github
000000f0:  2e63 6f6d 2f67 6f6f 676c 652f 7368 616b 612d 7061 636b 6167  :.com/google/shaka-packag
00000108:  6572 0035 6266 3861 6435 652d 7265 6c65 6173 6500 0002 7574  :er.5bf8ad5e-release...ut
00000120:  7261 6b00 0000 5c74 6b68 6400 0000 07dc cc27 a5dc cc27 a500  :rak...\tkhd......'...'..
00000138:  0000 0100 0000 0000 0000 0000 0000 0000 0000 0000 0000 0001  :........................
00000150:  0000 0000 0100 0000 0000 0000 0000 0000 0000 0000 0100 0000  :........................
00000168:  0000 0000 0000 0000 0000 0040 0000 0000 0000 0000 0000 0000  :...........@............
00000180:  0001 ed6d 6469 6100 0000 206d 6468 6400 0000 00dc cc27 a5dc  :...mdia... mdhd......'..
00000198:  cc27 a500 00ac 4400 0000 0055 c400 0000 0000 2d68 646c 7200  :.'....D....U......-hdlr.
000001b0:  0000 0000 0000 0073 6f75 6e00 0000 0000 0000 0000 0000 0053  :.......soun............S
000001c8:  6f75 6e64 4861 6e64 6c65 7200 0000 0198 6d69 6e66 0000 0024  :oundHandler.....minf...$
000001e0:  6469 6e66 0000 001c 6472 6566 0000 0000 0000 0001 0000 000c  :dinf....dref............
000001f8:  7572 6c20 0000 0001 0000 015c 7374 626c 0000 00f6 7374 7364  :url .......\stbl....stsd
00000210:  0000 0000 0000 0002 0000 009b 656e 6361 0000 0000 0000 0001  :............enca........
00000228:  0000 0000 0000 0000 0002 0010 0000 0000 ac44 0000 0000 0027  :.................D.....'
00000240:  6573 6473 0000 0000 0319 0001 0004 1140 1500 0000 0001 f403  :esds...........@........
00000258:  0001 f403 0502 1210 0601 0200 0000 5073 696e 6600 0000 0c66  :..............Psinf....f
00000270:  726d 616d 7034 6100 0000 1473 6368 6d00 0000 0063 656e 6300  :rmamp4a....schm....cenc.
00000288:  0100 0000 0000 2873 6368 6900 0000 2074 656e 6300 0000 0000  :......(schi... tenc.....
000002a0:  0001 0890 bf8c 4f4e 36d4 db87 62fa 2b94 59e5 b200 0000 4b6d  :......ON6...b.+.Y.....Km
000002b8:  7034 6100 0000 0000 0000 0100 0000 0000 0000 0000 0200 1000  :p4a.....................
000002d0:  0000 00ac 4400 0000 0000 2765 7364 7300 0000 0003 1900 0100  :....D.....'esds.........
000002e8:  0411 4015 0000 0000 01f4 0300 01f4 0305 0212 1006 0102 0000  :..@.....................
00000300:  0010 7374 7473 0000 0000 0000 0000 0000 0010 7374 7363 0000  :..stts............stsc..
00000318:  0000 0000 0000 0000 0014 7374 737a 0000 0000 0000 0000 0000  :..........stsz..........
00000330:  0000 0000 0010 7374 636f 0000 0000 0000 0000 0000 001a 7367  :......stco............sg
00000348:  7064 0100 0000 726f 6c6c 0000 0002 0000 0001 ffff 0000 0010  :pd....roll..............
00000360:  736d 6864 0000 0000 0000 0000 0000 0024 6564 7473 0000 001c  :smhd...........$edts....
00000378:  656c 7374 0000 0000 0000 0001 0000 0000 0000 0800 0001 0000  :elst....................
00000390:  0000 0038 6d76 6578 0000 0010 6d65 6864 0000 0000 00bc fa80  :...8mvex....mehd........
000003a8:  0000 0020 7472 6578 0000 0000 0000 0001 0000 0001 0000 0400  :... trex................
000003c0:  0000 0000 0000 0000 0000 0053 7073 7368 0000 0000 edef 8ba9  :...........Spssh........
000003d8:  79d6 4ace a3c8 27dc d51d 21ed 0000 0033 0801 1210 90bf 8c4f  :y.J...'...!....3.......O
000003f0:  4e36 d4db 8762 fa2b 9459 e5b2 1a07 7370 6f74 6966 7922 1490  :N6...b.+.Y....spotify"..
00000408:  bf8c 4f4e 36d4 db87 62fa 2b94 59e5 b29b ebda 6e00 0001 7c73  :..ON6...b.+.Y.....n...|s
00000420:  6964 7800 0000 0000 0000 0100 00ac 4400 0000 0000 0000 0000  :idx...........D.........
00000438:  0000 1d00 027d 1f00 06bc 0090 0000 0000 0286 a300 06bc 0090  :.....}..................
00000450:  0000 0000 0284 d600 06b8 0090 0000 0000 0286 7d00 06bc 0090  :..................}.....
00000468:  0000 0000 0285 af00 06bc 0090 0000 0000 0286 5a00 06b8 0090  :..................Z.....
00000480:  0000 0000 0285 9e00 06bc 0090 0000 0000 0285 9600 06bc 0090  :........................
00000498:  0000 0000 0284 8000 06b8 0090 0000 0000 0286 1400 06bc 0090  :........................
000004b0:  0000 0000 0287 0c00 06bc 0090 0000 0000 0284 bb00 06b8 0090  :........................
000004c8:  0000 0000 0287 3c00 06bc 0090 0000 0000 0287 4400 06bc 0090  :......<...........D.....
000004e0:  0000 0000 0284 f000 06b8 0090 0000 0000 0285 e400 06bc 0090  :........................
000004f8:  0000 0000 0285 bc00 06bc 0090 0000 0000 0285 dc00 06b8 0090  :........................
00000510:  0000 0000 0286 4800 06bc 0090 0000 0000 0285 8000 06bc 0090  :......H.................
00000528:  0000 0000 0284 9700 06b8 0090 0000 0000 0286 e200 06bc 0090  :........................
00000540:  0000 0000 0286 2e00 06bc 0090 0000 0000 0284 fd00 06b8 0090  :........................
00000558:  0000 0000 0287 0200 06bc 0090 0000 0000 0286 2900 06bc 0090  :..................).....
00000570:  0000 0000 0285 8600 06b8 0090 0000 0000 0286 6b00 06bc 0090  :..................k.....
00000588:  0000 0000 0032 6500 0086 8090 0000 0000 0007 406d 6f6f 6600  :.....2e...........@moof.
000005a0:  0000 106d 6668 6400 0000 0000 0000 0100 0007 2874 7261 6600  :...mfhd...........(traf.
000005b8:  0000 1c74 6668 6400 0200 2a00 0000 0100 0000 0200 0004 0000  :...tfhd...*.............
000005d0:  0000 0000 0000 1074 6664 7400 0000 0000 0000 0000 0006 d874  :.......tfdt............t
000005e8:  7275 6e00 0002 0100 0001 b100 0007 4800 0001 7300 0001 7400  :run...........H...s...t.
[i gues mp4 of segment 1 ]

-> Header of segment 2
000282a8:  0e0c b495 0250 00d6 bca6 7be1 6807 0000 14e5 6d6f 6f66 0000  :.....P....{.h.....moof..
000282c0:  0010 6d66 6864 0000 0000 0000 0002 0000 14cd 7472 6166 0000  :..mfhd............traf..
000282d8:  001c 7466 6864 0002 002a 0000 0001 0000 0001 0000 0400 0000  :..tfhd...*..............
000282f0:  0000 0000 0010 7466 6474 0000 0000 0006 c400 0000 06d0 7472  :......tfdt............tr
00028308:  756e 0000 0201 0000 01af 0000 14ed 0000 016f 0000 0165 0000  :un...............o...e..

-> mp4 again

-> Header of segment 3
000282a8:  0e0c b495 0250 00d6 bca6 7be1 6807 0000 14e5 6d6f 6f66 0000  :.....P....{.h.....moof..
000282c0:  0010 6d66 6864 0000 0000 0000 0002 0000 14cd 7472 6166 0000  :..mfhd............traf..
000282d8:  001c 7466 6864 0002 002a 0000 0001 0000 0001 0000 0400 0000  :..tfhd...*..............
000282f0:  0000 0000 0010 7466 6474 0000 0000 0006 c400 0000 06d0 7472  :......tfdt............tr
00028308:  756e 0000 0201 0000 01af 0000 14ed 0000 016f 0000 0165 0000  :un...............o...e..

`

i guess playback stops after 10s because VLC does not expect the dash header

**Comment by timdorr** [comment]
Well, it's definitely encrypted:

```
Found 1 stream(s).
Stream [0] type: Audio
 codec_string: mp4a.40.2
 time_scale: 44100
 duration: 485928952 (11018.8 seconds)
 is_encrypted: true
 codec: AAC
 sample_bits: 16
 num_channels: 2
 sampling_frequency: 44100
 language: und
 seek_preroll_ns: 22675
```

It's using CENC and the pssh comes from that Widevine endpoint. I'm learning all about this as I go, so sorry if I'm stating the obvious here. 

I don't really see a way around that. You'd need to decrypt the audio for any exclusive podcast. While the keys are in the clear and don't require authentication, you've still got to actually host that content somewhere. That's going to be headed into not-legal territory, which isn't something I'm personally interested in. I'm more than happy to support forks that want to take on the risk, but I don't think it's going to happen here unfortunately.

**Comment by yoshimo** [comment]
Maybe this incident could be used instead to work with spotify on proper rss support and support for third party apps that includes support for premium content as it is being worked on in https://github.com/Podcastindex-org/podcast-namespace/issues/239 and other issues in that repository.

Work could also be done on podcatchers to make use of the underlying widevine api which is already used for video streaming services as well and supported by the mobile os directly.

**Comment by LeoNatan** [comment]
@yoshimo Thats a naive look at things. Spotify JS no incentive to let these podcasts go outside their own app and/or ecosystem. They didnt pay large sums for exclusivity, just to act as a host for third party apps.

**Comment by marc1307** [comment]
Hi,
they have changed something again. The webclient serves mp3 files again

ex: 
https://open.spotify.com/episode/3TrZPFh2aI4tEngMcW2rAt
plays this media:
https://dcs.megaphone.fm/GLT6531345056.mp3?key=bf855f907eafb6c231c4dbdc6fa48f72

The key does not seem to be important.
verified with another exclusive show -> works the same

**Comment by neodyne** [comment]
@marc1307 with external podcasts, the `externallyHosted` field for a particular episode was always populated in the gql response, it just wasn't really needed, because feeds for those podcasts are/were public. For the originals/exclusive podcasts, where an episode url on megaphone is known (e.g. `https://traffic.megaphone.fm/GLT6531345056.mp3` ), you can use the megaphone api to get the (original) feed url on megaphone, bypassing the need to construct the feed anew from spotify api data entirely.

**Comment by Funatiker** [comment]
> you can use the megaphone api to get the (original) feed url on megaphone

@neodyne How?

**Comment by neodyne** [comment]
@Funatiker At `https://player.megaphone.fm/playlist/episode/$episode_id`, where `$episode_id` is the mp3 file of any particular episode of a podcast without extension, check the `podcastFeedUrl` field.

In (ugly) Python (for educational purposes of course):

```
#!/usr/bin/env python3

import json
from urllib import request

id='GLT6531345056' # https://traffic.megaphone.fm/GLT6531345056.mp3
url=json.loads(request.urlopen('https://player.megaphone.fm/playlist/episode/'+id).read().decode('utf-8'))['podcastFeedUrl']
print(url)
```

The problem is, as was observed above, more often than not with **original (audio) podcasts** the gql response (and/or the web player/embed) doesn't leak the url to the megaphone-hosted mp3s, even if they are most likely sourced the same way (I am pretty sure that even for those podcasts megaphone rss feeds exist, spotify seems to rely on the megaphone infrastructure a lot).

**Comment by toastp** [comment]
Out of curiosity, can anyone point me to where I can find the key for decryption?

**Comment by mimmiechan** [comment]
> You'd need to decrypt the audio for any exclusive podcast. While the keys are in the clear and don't require authentication, you've still got to actually host that content somewhere. That's going to be headed into not-legal territory, which isn't something I'm personally interested in. I'm more than happy to support forks that want to take on the risk, but I don't think it's going to happen here unfortunately.

I don't understand athe technical details, but couldn't you make a front end app that decrypts and downloads the audio to the user's device, and then generates an rss feed file that links to the local audio files? The user would then add this RSS to their podcast player. The app could download and update the feed in the background per schedule, or on-demand by the user. I guess not every podcast player supports adding rss feeds from local files. Possibly use private network as workaround for these cases?

Honestly, even an app that just DL's the audio to playable files would be useful for me. Then I can just add the DL folder as a podcast in AntennaPod.
